basePath: /
definitions:
  handler.changeBalance:
    properties:
      balance:
        type: integer
    type: object
  handler.deleteAccount:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  handler.signInInput:
    properties:
      login:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - login
    - password
    type: object
  handler.signUp:
    properties:
      login:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - login
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Online Shop Application
  title: onlineShop App API
  version: "1.0"
paths:
  /api/users/:
    get:
      description: get list of users
      parameters:
      - description: Authentication Token
        in: header
        name: X-Auth-Token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get Userlist
      tags:
      - users
  /api/users/:id:
    delete:
      consumes:
      - application/json
      description: delete user or change user acc to inactive
      parameters:
      - description: User data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.deleteAccount'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - users
    get:
      description: get user by id
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get User
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update balance of user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: NewBalance
        in: body
        name: balance
        required: true
        schema:
          $ref: '#/definitions/handler.changeBalance'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - users
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: reg input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signUp'
      produces:
      - application/json
      responses: {}
      summary: SignUp
      tags:
      - auth
swagger: "2.0"
