basePath: /
definitions:
  models.UpdateProduct:
    properties:
      amount:
        type: integer
      cost:
        type: number
      description:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Online Shop Application
  title: onlineShop App API
  version: "1.0"
paths:
  /api/cart/:
    get:
      consumes:
      - application/json
      description: get cart by your id from database
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Check your cart
      tags:
      - cart
  /api/cart/add:
    post:
      consumes:
      - application/json
      description: add product to your cart by id and amount of product
      parameters:
      - description: Id of product
        in: query
        name: productId
        required: true
        type: integer
      - description: Quantity of product
        in: query
        name: quantity
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Add product to your cart
      tags:
      - cart
  /api/cart/order:
    post:
      consumes:
      - application/json
      description: create order from your cart
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Make order
      tags:
      - cart
  /api/orders/:
    get:
      consumes:
      - application/json
      description: get your orders list from database
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get orderList
      tags:
      - orders
  /api/orders/{id}:
    get:
      consumes:
      - application/json
      description: get order by id from database
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get order by id
      tags:
      - orders
  /api/products/:
    get:
      consumes:
      - application/json
      description: get product list from database
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get productlist
      tags:
      - products
    post:
      consumes:
      - application/json
      description: add product to database
      parameters:
      - description: product name
        in: query
        name: name
        required: true
        type: string
      - description: price for product
        in: query
        name: cost
        required: true
        type: number
      - description: product description
        in: query
        name: description
        type: string
      - description: amount of product
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Add product
      tags:
      - products
  /api/products/{id}:
    delete:
      consumes:
      - application/json
      description: delete product by id from database
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete product by id
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get product by id from database
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get product by id
      tags:
      - products
    put:
      consumes:
      - application/json
      description: change name, cost or amount of product from database
      parameters:
      - description: NewProduct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProduct'
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Change info about product
      tags:
      - products
  /api/users/:
    delete:
      consumes:
      - application/json
      description: delete user or change user acc to inactive
      parameters:
      - description: your login
        in: query
        name: login
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - users
    get:
      description: get list of users
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get Userlist
      tags:
      - users
  /api/users/{id}:
    get:
      description: get user by id
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get User
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update balance of user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: how many money do you want add/receive(type with -)
        in: query
        name: balance
        required: true
        type: number
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - users
  /api/users/link/{service}:
    post:
      consumes:
      - application/json
      description: link your account with another service
      parameters:
      - description: service
        in: path
        name: service
        required: true
        type: string
      - description: your login
        in: query
        name: login
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: link account
      tags:
      - users
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: your login
        in: query
        name: login
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: your login
        in: query
        name: login
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      - description: your email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
